 ///////////////////////////////////////////////////// 
 // Note that this file was generated by VProfiler. // 
 // Please do not change the contents of this file! // 
 ///////////////////////////////////////////////////// 

#ifndef VPROFEVENTWRAPPERS_H
#define VPROFEVENTWRAPPERS_H
#include "trace_tool.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif