// VProf libs
#include "Utils.h"

// STL libs
#include <memory>
#include <unordered_map>
#include <string>
#include <vector>
#include <fstream>
#include <stdexcept>
#include <algorithm>

struct LogInformation {
    unsigned int functionID;
    bool isMessageBased; 
};

class FunctionFileReader {
    public:
        FunctionFileReader(const std::string _filename): filename(_filename),
        funcMap(), logInfoMap(), unqualifiedNames(), beenParsed(false) {}
        
        // Parse the file
        void Parse();

        // Returns the function map generated by parse.
        // Parse must be called prior to this.
        std::unordered_map<std::string, std::string> GetFunctionMap();

        // Returns a map of qualified function name to log info struct
        std::unordered_map<std::string, LogInformation> GetLogInfoMap();

        // Returns a vector of all the qualified function names.
        // Parse must be called prior to this.
        std::vector<std::string> GetQualifiedFunctionNames();

        // Returns a vector of all the unqualified function names.
        // Parse must be called prior to this.
        std::vector<std::string> GetUnqualifiedFunctionNames();

    private:
        const std::string filename;
        std::unordered_map<std::string, std::string> funcMap;
        std::unordered_map<std::string, LogInformation> logInfoMap;
        std::vector<std::string> unqualifiedNames;
        std::vector<std::string> qualifiedNames;

        bool beenParsed;
};
