 ///////////////////////////////////////////////////// 
 // Note that this file was generated by VProfiler. // 
 // Please do not change the contents of this file! // 
 ///////////////////////////////////////////////////// 

#include "./Classes.h"
#include "TraceTool.h"

class B A__getb_vprofiler(class A * obj);

void D_int___setD_vprofiler(class D<int> * obj, int val);

