 ///////////////////////////////////////////////////// 
 // Note that this file was generated by VProfiler. // 
 // Please do not change the contents of this file! // 
 ///////////////////////////////////////////////////// 

#include "/home/jiamin/httpd/srclib/apr/include/apr_thread_cond.h"
#include "/home/jiamin/httpd/srclib/apr/include/apr_thread_mutex.h"
#include "/home/jiamin/httpd/srclib/apr/include/apr_global_mutex.h"
#include "/home/jiamin/httpd/srclib/apr/include/apr_proc_mutex.h"
#include "trace_tool.h"

apr_status_t apr_thread_cond_broadcast_vprofiler(apr_thread_cond_t * cond);

apr_status_t apr_thread_cond_wait_vprofiler(apr_thread_cond_t * cond, apr_thread_mutex_t * mutex);

apr_status_t apr_thread_mutex_unlock_vprofiler(apr_thread_mutex_t * mutex);

apr_status_t apr_thread_cond_signal_vprofiler(apr_thread_cond_t * cond);

apr_status_t apr_thread_mutex_lock_vprofiler(apr_thread_mutex_t * mutex);

apr_status_t apr_global_mutex_lock_vprofiler(apr_global_mutex_t * mutex);

apr_status_t apr_global_mutex_unlock_vprofiler(apr_global_mutex_t * mutex);

apr_status_t apr_proc_mutex_lock_vprofiler(apr_proc_mutex_t * mutex);

apr_status_t apr_proc_mutex_unlock_vprofiler(apr_proc_mutex_t * mutex);
