INSTALL_PREFIX = /usr/local

.PHONY: install
install:
	mkdir -p $(DESTDIR)$(INSTALL_PREFIX)/share/vprofiler/FactorSelector
	cp *.py $(DESTDIR)$(INSTALL_PREFIX)/share/vprofiler/FactorSelector
	cp -r CriticalPathBuilder $(DESTDIR)$(INSTALL_PREFIX)/share/vprofiler/FactorSelector
